### ISSUE TITLE
index.handler is undefined or not exported

### ISSUE THREAD

**Issue by jmzn** [brain-power/Brain-Power-Amazon-Fidgetology#28]
Hi,

I am seeing the following error in my API Gateway ""index.handler is undefined or not exported" as you can see below:

Fri Apr 17 18:23:22 UTC 2020 : Sending request to https://lambda.us-east-1.amazonaws.com/2015-03-31/functions/arn:aws:lambda:us-east-1:XXXXXXXXXXXX:function:brain-WebAPI-S7UEBDW371IM/invocations
Fri Apr 17 18:23:22 UTC 2020 : Received response. Status: 200, Integration latency: 154 ms
Fri Apr 17 18:23:22 UTC 2020 : Endpoint response headers: {Date=Fri, 17 Apr 2020 18:23:22 GMT, Content-Type=application/json, Content-Length=839, Connection=keep-alive, x-amzn-RequestId=037a86de-479d-4b74-80d1-1398aec85561, X-Amz-Function-Error=Unhandled, x-amzn-Remapped-Content-Length=0, X-Amz-Executed-Version=$LATEST, X-Amzn-Trace-Id=root=1-5abe31a-6ab7a3545768546468184;sampled=0}
Fri Apr 17 18:23:22 UTC 2020 : Endpoint response body before transformations: {"errorType":"Runtime.HandlerNotFound","errorMessage":"index.handler is undefined or not exported","trace":["**Runtime.HandlerNotFound: index.handler is undefined or not exported"**,"    at Object.module.exports.load (/var/runtime/UserFunction.js:144:11)","    at Object.<anonymous> (/var/runtime/index.js:45:30)","    at Module._compile (internal/modules/cjs/loader.js:778:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)","    at Module.load (internal/modules/cjs/loader.js:653:32)","    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)","    at Function.Module._load (internal/modules/cjs/loader.js:585:3)","    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)","    at startup (internal/bootstrap/node.js:283:19)","    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)"]}
Fri Apr 17 18:23:22 UTC 2020 : Lambda execution failed with status 200 due to customer function error: index.handler is undefined or not exported. Lambda request id: 187a86de-4acd-4124-80d1-13ca43565561
Fri Apr 17 18:23:22 UTC 2020 : Method completed with status: 502

I am wondering if you would be able to help?

Thanks!

**Comment by jmzn** [comment]
This was my mistake when uploading the code to lambda.
